### PR TITLE
(pal) Port @svofski's CRT shader to libretro.

### PR DESCRIPTION
**Pull request by rz5**
Tried to add the phase noise feature found in his crt.py software
version.

@svofski - Hi. I couldn't find anything in your repo about your GLSL shaders's licenses. Any choices?

### CODE REVIEW

**Comment by svofski** [comment]
Hi. I did not really think about it, it's just a playground project of mine. I wouldn't want it to be restrictive. Let's assume it's a 2-clause BSD licence.

**Comment by rz5** [comment]
@svofski Hi again, if you memory is still fresh about the project, I noticed that in your Python implementations of PAL processing you optionally add phase noise to the image, in between the encoding and decoding steps.

But the GLSL shaders lack that. I added something to that effect, making sure to add noise only along the horizontal axis (so you get some weaving/jitter).
Would you say [this is the right place](https://github.com/hizzlekizzle/slang-shaders/blob/master/pal/pal-singlepass.slang#L159#L167) to be adding randomness to the phase?

**Comment by svofski** [comment]
hi @rz5,
I think I just didn't find good enough parameters for it to look nice, or maybe I could not make it usable in the context of SDLMESS, the details I can't remember. Let's see about your addition.

In a real TV I think the most phase noise variation would happen on a per-line basis, rather than on per-pixel basis. There is a part of the horizontal sync pulse where the colourburst is sent. The decoder uses it to lock on phase. If the signal is weak and noisy, there's a good chance that it will not lock on perfectly and there will be some chroma offset until the next line. You seem to be sampling the noise on a per-line basis, so this matches the way I see it. You then introduce this random offset between modulator and demodulator. Everything seems to add up. I would say this is the right place.

Does it look good (in relative terms) on screen?

**Comment by rz5** [comment]
@svofski, relatively good, yes. In some cases where there's a lot of blue color, the noise will make it flicker from blue to red. 
These following screenshots are have been taken without shaders and with the port of your shader, with PHASE_NOISE set to 1.0:

retroarch-0723-003044
retroarch-0723-003034

retroarch-0723-003352
retroarch-0723-003429

**Comment by hizzlekizzle** [comment]
Since we have a framecounter, is there somewhere we could add in a dot-crawl effect?

**Comment by svofski** [comment]
These looks pretty convincing. 

BTW, did you see my experiments in the gosha branch?
https://github.com/svofski/CRT/blob/gosha/gosha/shaders/singlescan/pass1.fsh
These are more messy but I had some success emulating trinitron-ish RGB triads. It's impossible to do it properly on a low resolution LCD but it's an interesting option I think.

**Comment by rz5** [comment]
@svofski, Trinitron triads huh? I didn't notice you had more branches in that repo, no. Do you have pictures of how it looks like?
If it gets close to what a specific Trinitron model looks like, I'd be interested in porting that to libretro too if you don't mind.

If you are a fan of CRT display emulation, you really ought to look to what we already have in the [common-shaders repo](https://github.com/libretro/common-shaders/tree/master/crt/shaders).
In particular, there is this monster of a multipass shader called crt-royale which exposes a lot of parameters.
Users have tweaked the params to make it look convincingly like one of those Sony PVM monitors: http://libretro.com/forums/showthread.php?t=4909&page=13&p=41656&viewfull=1#post41656

Because of your work on the PAL shader, we'll potentially be able to chain crt-royale together with this and get some accurate European image degradation.

**Comment by svofski** [comment]
I did not have a particular model in mind. Just took some closeup pictures of a MSX monitor and tried to get something close. The results were okay-ish, but I cannot really brag that I achieved perfection in this, If you're working on these shaders it might be of some interest for you to see.

The crt-royale screenshots in your link look fantastic. 

It's been a while and the memory of that project fades, but let me know if I can help somehow.

**Pull request merged**
